import { TaskStatus, TaskCategory, EssayStatus } from '@prisma/client';

export const mockStudentTasks = [
  {
    id: 'mock-1',
    title: 'Research Target Colleges',
    description: 'Create a balanced list of reach, target, and safety schools',
    category: TaskCategory.APPLICATION,
    status: TaskStatus.IN_PROGRESS,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Aug–Oct, Senior year',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-2',
    title: 'Draft Common App Essay',
    description: 'Write first draft of main Common Application essay (650 words)',
    category: TaskCategory.ESSAY,
    status: TaskStatus.IN_PROGRESS,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Sep–Oct, Senior year',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-3',
    title: 'Take SAT/ACT',
    description: 'Complete standardized testing',
    category: TaskCategory.TESTING,
    status: TaskStatus.COMPLETED,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Junior year',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-4',
    title: 'Request Teacher Recommendations',
    description: 'Ask 2–3 teachers for letters of recommendation',
    category: TaskCategory.APPLICATION,
    status: TaskStatus.COMPLETED,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Spring–Summer, Junior year',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-5',
    title: 'Campus Visits',
    description: 'Visit schools and attend information sessions',
    category: TaskCategory.OTHER,
    status: TaskStatus.IN_PROGRESS,
    priority: 2,
    dueDate: null as Date | null,
    dueLabel: 'Oct–Nov, Senior year',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockParentTasks = [
  {
    id: 'mock-p1',
    title: 'Complete FAFSA',
    description: 'Submit Free Application for Federal Student Aid',
    category: TaskCategory.FAFSA,
    status: TaskStatus.NOT_STARTED,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Oct–Mar (verify at studentaid.gov)',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-p2',
    title: 'Submit CSS Profile',
    description: 'Complete CSS Profile for institutional aid',
    category: TaskCategory.CSS_PROFILE,
    status: TaskStatus.NOT_STARTED,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Oct–Feb (varies by school)',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-p3',
    title: 'Research Scholarships',
    description: 'Identify external scholarship opportunities',
    category: TaskCategory.SCHOLARSHIP,
    status: TaskStatus.IN_PROGRESS,
    priority: 2,
    dueDate: null as Date | null,
    dueLabel: 'Year-round',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-p4',
    title: 'Gather Financial Documents',
    description: 'Collect tax returns, W-2s, and other financial records',
    category: TaskCategory.FINANCIAL_AID,
    status: TaskStatus.IN_PROGRESS,
    priority: 1,
    dueDate: null as Date | null,
    dueLabel: 'Oct–Jan',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockEssays = [
  {
    id: 'mock-e1',
    title: 'Common App Main Essay',
    prompt: 'Some students have a background, identity, interest, or talent that is so meaningful they believe their application would be incomplete without it. If this sounds like you, then please share your story.',
    content: '',
    wordCount: 0,
    status: EssayStatus.DRAFT,
    schoolName: 'Common Application',
    dueDate: null as Date | null,
    dueLabel: 'Nov–Jan (varies by school)',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'mock-e2',
    title: 'Stanford — Intellectual Vitality',
    prompt: 'The Stanford community is deeply curious and driven to learn in and out of the classroom. Reflect on an idea or experience that makes you genuinely excited about learning.',
    content: '',
    wordCount: 0,
    status: EssayStatus.DRAFT,
    schoolName: 'Stanford University',
    dueDate: null as Date | null,
    dueLabel: 'Jan (verify with Stanford)',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockBudgets = [
  {
    id: 'mock-b1',
    schoolName: 'State University',
    tuitionCost: 12000,
    roomAndBoard: 14000,
    booksAndSupplies: 1200,
    otherExpenses: 2000,
    expectedAid: 8000,
    scholarships: 3000,
    notes: 'In-state tuition. Merit scholarship likely.',
  },
  {
    id: 'mock-b2',
    schoolName: 'Private College',
    tuitionCost: 55000,
    roomAndBoard: 16000,
    booksAndSupplies: 1500,
    otherExpenses: 2500,
    expectedAid: 35000,
    scholarships: 5000,
    notes: 'Need-based aid estimate from net price calculator.',
  },
  {
    id: 'mock-b3',
    schoolName: 'Public University (Out-of-State)',
    tuitionCost: 28000,
    roomAndBoard: 13000,
    booksAndSupplies: 1100,
    otherExpenses: 2200,
    expectedAid: 10000,
    scholarships: 2000,
    notes: 'Out-of-state. Possible merit aid.',
  },
];

export const mockStudentProgress = {
  totalTasks: 5,
  completedTasks: 2,
  inProgressTasks: 2,
  overdueTasks: 0,
  upcomingDeadlines: mockStudentTasks.filter((t) => t.status !== TaskStatus.COMPLETED).slice(0, 3),
  essayProgress: {
    total: 2,
    draft: 2,
    inReview: 0,
    final: 0,
  },
};
